'use client';

import { useEffect, useState } from 'react';
import { Loader2, Save, Settings } from '@/components/icons';
import { useToast } from '@/components/Toaster';

interface Props { eventId: string; isAdmin?: boolean; }
export default function EventSettingsManager({ eventId, isAdmin = false }: Props) {
  const { showToast } = useToast();
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false);
  const [capacity, setCapacity] = useState(''); const [timezone, setTimezone] = useState('Asia/Kolkata');
  const [manualEnabled, setManualEnabled] = useState(true); const [allowUndo, setAllowUndo] = useState(true); const [lowLightMode, setLowLightMode] = useState(false); const [staffAccessIds, setStaffAccessIds] = useState('');
  useEffect(() => { let active = true; setLoading(true); fetch(`/api/events/${encodeURIComponent(eventId)}/settings`, { cache: 'no-store' }).then(async (res) => { const data = await res.json(); if (!res.ok) throw new Error(data.error || 'Failed to load event settings'); if (!active) return; setCapacity(String(data.capacity || '')); setTimezone(data.timezone || 'Asia/Kolkata'); setManualEnabled(data.checkIn?.manualEnabled !== false); setAllowUndo(data.checkIn?.allowUndo !== false); setLowLightMode(data.checkIn?.lowLightMode === true); setStaffAccessIds((data.staffAccessIds || []).join(', ')); }).catch((error) => showToast(error instanceof Error ? error.message : 'Failed to load event settings', 'error')).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [eventId, showToast]);
  const save = async () => { setSaving(true); try { const res = await fetch(`/api/events/${encodeURIComponent(eventId)}/settings`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ timezone, capacity: isAdmin ? Number(capacity) : undefined, staffAccessIds: isAdmin ? staffAccessIds.split(',').map((value) => value.trim()).filter(Boolean) : undefined, checkIn: { manualEnabled, allowUndo, lowLightMode } }) }); const data = await res.json(); if (!res.ok) throw new Error(data.error || 'Failed to save event settings'); showToast('Event settings saved', 'success'); } catch (error) { showToast(error instanceof Error ? error.message : 'Failed to save event settings', 'error'); } finally { setSaving(false); } };
  if (loading) return <div className="flex items-center gap-2 text-sm text-zinc-500"><Loader2 className="h-4 w-4 animate-spin" />Loading event settings…</div>;
  return <section className="rounded-2xl border border-zinc-800 bg-zinc-900 p-5 text-white"><h3 className="flex items-center gap-2 font-semibold"><Settings className="h-4 w-4 text-blue-400" />Event workspace settings</h3><p className="mt-1 text-xs text-zinc-500">These rules are scoped to the selected event.</p><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-sm text-zinc-400">Timezone<select value={timezone} onChange={(e) => setTimezone(e.target.value)} className="mt-1 w-full rounded-lg border border-zinc-700 bg-zinc-950 px-3 py-2 text-white"><option>Asia/Kolkata</option><option>UTC</option><option>America/New_York</option><option>Europe/London</option><option>Asia/Singapore</option></select></label>{isAdmin && <label className="text-sm text-zinc-400">Capacity<input type="number" min="1" value={capacity} onChange={(e) => setCapacity(e.target.value)} className="mt-1 w-full rounded-lg border border-zinc-700 bg-zinc-950 px-3 py-2 text-white" /></label>}</div><div className="mt-4 space-y-3 text-sm"><label className="flex items-center justify-between gap-3"><span>Allow approved manual check-ins</span><input type="checkbox" checked={manualEnabled} onChange={(e) => setManualEnabled(e.target.checked)} /></label><label className="flex items-center justify-between gap-3"><span>Allow undo check-in</span><input type="checkbox" checked={allowUndo} onChange={(e) => setAllowUndo(e.target.checked)} /></label><label className="flex items-center justify-between gap-3"><span>Low-light scanner mode default</span><input type="checkbox" checked={lowLightMode} onChange={(e) => setLowLightMode(e.target.checked)} /></label></div>{isAdmin && <label className="mt-4 block text-sm text-zinc-400">Staff access IDs<span className="mt-1 block text-xs text-zinc-600">Comma-separated Clerk user IDs. Event assignments remain the authorization source.</span><input value={staffAccessIds} onChange={(e) => setStaffAccessIds(e.target.value)} className="mt-1 w-full rounded-lg border border-zinc-700 bg-zinc-950 px-3 py-2 text-white" placeholder="user_..." /></label>}<button onClick={() => void save()} disabled={saving} className="mt-5 flex items-center gap-2 rounded-lg bg-blue-600 px-4 py-2 text-sm font-medium disabled:opacity-50"><Save className="h-4 w-4" />{saving ? 'Saving…' : 'Save settings'}</button></section>;
}
