/**
 * Barrel export for the most common lucide-react icons used across the app.
 * Importing from '@/components/icons' is shorter and tree-shakable.
 *
 * To add a new icon: import it from 'lucide-react' here and re-export it.
 * Do not import from 'lucide-react' directly anywhere else in the app —
 * the eslint config enforces this via `no-restricted-imports`.
 */
export {
    Activity,
    AlertCircle,
    AlertTriangle,
    ArrowLeft,
    ArrowRight,
    Award,
    BarChart,
    BarChart3,
    BarChart as BarChartIcon,
    Bell,
    Calendar,
    CalendarDays,
    Camera,
    Check,
    CheckCircle,
    CheckCircle2,
    CheckSquare,
    ChevronDown,
    ChevronRight,
    ClipboardList,
    Clock,
    CloudOff,
    Copy,
    CreditCard,
    DollarSign,
    Download,
    Edit,
    Edit3,
    ExternalLink,
    Eye,
    EyeOff,
    FileSpreadsheet,
    FileText,
    Filter,
    Flashlight,
    FlashlightOff,
    Globe,
    GripVertical,
    HelpCircle,
    History,
    Home,
    Home as HomeIcon,
    Image,
    Image as ImageIcon,
    Info,
    Layout,
    LayoutDashboard,
    Lightbulb,
    Loader2,
    Lock,
    LogIn,
    LogOut,
    Mail,
    Map,
    MapPin,
    Menu,
    MessageSquare,
    Palette,
    PartyPopper,
    Pause,
    Pencil,
    Phone,
    Play,
    Plus,
    Power,
    Power as PowerOn,
    Radio,
    Receipt,
    ReceiptText,
    RefreshCw,
    RotateCcw,
    Save,
    Scan,
    ScanLine,
    Search,
    Send,
    Settings,
    Settings as SettingsIcon,
    Share2,
    Shield,
    ShieldCheck,
    ShoppingBag,
    Smartphone,
    Sparkles,
    Square,
    Star,
    Tag,
    Tent,
    ThumbsUp,
    Ticket,
    Ticket as TicketIcon,
    ToggleLeft,
    ToggleRight,
    Trash2,
    TrendingUp,
    Trophy,
    Undo2,
    Upload,
    User,
    UserCheck,
    Users,
    Video,
    Wifi,
    WifiOff,
    X,
    XCircle,
} from 'lucide-react';

export type { LucideIcon } from 'lucide-react';
