/**
 * Barrel export for the most common lucide-react icons used across the app.
 * Importing from '@/components/icons' is shorter and tree-shakable.
 */
export {
    AlertTriangle,
    Award,
    BarChart3,
    Bell,
    Calendar,
    CheckCircle,
    ChevronDown,
    Clock,
    Copy,
    Edit,
    Eye,
    EyeOff,
    FileText,
    Filter,
    Globe,
    GripVertical,
    History,
    Home,
    Layout,
    LayoutDashboard,
    LogOut,
    Mail,
    MessageSquare,
    Palette,
    Pause,
    Play,
    Plus,
    Power,
    Power as PowerOn,
    Receipt,
    Search,
    Settings as SettingsIcon,
    Shield,
    Smartphone,
    Star,
    Tag,
    Tent,
    Ticket,
    Trash2,
    TrendingUp,
    Users,
} from 'lucide-react';
