'use client';

import { useCallback, useEffect, useState } from 'react';
import { readJsonResponse } from '@/lib/client-response';

type EventOption = { id: string; name: string };
type Template = { id: string; name: string; description?: string | null; sourceEventId?: string | null; createdAt: string };

export default function EventTemplateManager({ events, isAdmin = false, onEventCreated }: { events: EventOption[]; isAdmin?: boolean; onEventCreated?: () => void }) {
  const [templates, setTemplates] = useState<Template[]>([]); const [sourceEventId, setSourceEventId] = useState(events[0]?.id || ''); const [name, setName] = useState(''); const [description, setDescription] = useState(''); const [createTemplateId, setCreateTemplateId] = useState(''); const [eventName, setEventName] = useState(''); const [eventDate, setEventDate] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [message, setMessage] = useState('');
  const load = useCallback(async () => { const response = await fetch('/api/admin/event-templates'); const data = await readJsonResponse<Template[] & { error?: string }>(response, 'Failed to load templates'); if (!response.ok) throw new Error(data.error || 'Failed to load templates'); setTemplates(data); }, []);
  useEffect(() => { load().catch((err) => setError(err.message)); }, [load]); useEffect(() => { if (!sourceEventId && events[0]) setSourceEventId(events[0].id); }, [events, sourceEventId]);
  const save = async () => { if (!sourceEventId || !name.trim()) return setError('Select an event and enter a template name'); setBusy(true); setError(''); setMessage(''); try { const response = await fetch('/api/admin/event-templates', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action: 'save', sourceEventId, name, description }) }); const data = await readJsonResponse<{ error?: string }>(response, 'Save failed'); if (!response.ok) throw new Error(data.error || 'Save failed'); setName(''); setDescription(''); setMessage('Template saved as an independent snapshot.'); await load(); } catch (err) { setError(err instanceof Error ? err.message : 'Save failed'); } finally { setBusy(false); } };
  const createEvent = async () => { if (!createTemplateId || !eventName.trim() || !eventDate) return setError('Choose a template, event name, and date'); setBusy(true); setError(''); setMessage(''); try { const response = await fetch('/api/admin/event-templates', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action: 'create-event', templateId: createTemplateId, eventName, eventDate: new Date(`${eventDate}T00:00:00.000Z`).toISOString() }) }); const data = await readJsonResponse<{ error?: string; name?: string }>(response, 'Event creation failed'); if (!response.ok) throw new Error(data.error || 'Event creation failed'); setMessage(`Draft event “${data.name}” created. Review and publish it from Events.`); setEventName(''); setEventDate(''); onEventCreated?.(); } catch (err) { setError(err instanceof Error ? err.message : 'Event creation failed'); } finally { setBusy(false); } };
  const remove = async (id: string) => { if (!confirm('Delete this event template?')) return; const response = await fetch(`/api/admin/event-templates?id=${encodeURIComponent(id)}`, { method: 'DELETE' }); if (response.ok) await load(); else setError((await readJsonResponse<{ error?: string }>(response, 'Delete failed')).error || 'Delete failed'); };
  return <div className="space-y-6"><div><h2 className="text-2xl font-bold text-white">Event Template Library</h2><p className="text-sm text-zinc-400">Save reusable event configuration snapshots without linking them to live event data.</p></div>{error && <div className="rounded-xl border border-red-900 bg-red-950/40 px-4 py-3 text-sm text-red-300">{error}</div>}{message && <div className="rounded-xl border border-green-900 bg-green-950/40 px-4 py-3 text-sm text-green-300">{message}</div>}
    <div className={`grid gap-6 ${isAdmin ? 'lg:grid-cols-2' : ''}`}><div className="rounded-2xl border border-zinc-800 bg-zinc-900 p-5"><h3 className="mb-4 font-semibold text-white">Save from an existing event</h3><div className="space-y-3"><select value={sourceEventId} onChange={(e) => setSourceEventId(e.target.value)} className="w-full rounded-xl border border-zinc-700 bg-zinc-950 px-4 py-3 text-white">{events.map((event) => <option key={event.id} value={event.id}>{event.name}</option>)}</select><input value={name} onChange={(e) => setName(e.target.value)} placeholder="Template name" className="w-full rounded-xl border border-zinc-700 bg-zinc-950 px-4 py-3 text-white"/><textarea value={description} onChange={(e) => setDescription(e.target.value)} placeholder="When should this template be used?" className="min-h-20 w-full rounded-xl border border-zinc-700 bg-zinc-950 px-4 py-3 text-white"/><button disabled={busy || !events.length} onClick={save} className="rounded-xl bg-red-600 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">Save template</button></div></div>
      {isAdmin && <div className="rounded-2xl border border-zinc-800 bg-zinc-900 p-5"><h3 className="mb-4 font-semibold text-white">Create a draft event</h3><div className="space-y-3"><select value={createTemplateId} onChange={(e) => setCreateTemplateId(e.target.value)} className="w-full rounded-xl border border-zinc-700 bg-zinc-950 px-4 py-3 text-white"><option value="">Choose template</option>{templates.map((template) => <option key={template.id} value={template.id}>{template.name}</option>)}</select><input value={eventName} onChange={(e) => setEventName(e.target.value)} placeholder="New event name" className="w-full rounded-xl border border-zinc-700 bg-zinc-950 px-4 py-3 text-white"/><input type="date" value={eventDate} onChange={(e) => setEventDate(e.target.value)} className="w-full rounded-xl border border-zinc-700 bg-zinc-950 px-4 py-3 text-white"/><button disabled={busy || !templates.length} onClick={createEvent} className="rounded-xl bg-red-600 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">Create unpublished draft</button></div></div>}</div>
    <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{templates.map((template) => <div key={template.id} className="rounded-2xl border border-zinc-800 bg-zinc-900 p-5"><h3 className="font-semibold text-white">{template.name}</h3>{template.description && <p className="mt-2 text-sm text-zinc-400">{template.description}</p>}<p className="mt-3 text-xs text-zinc-600">Saved {new Date(template.createdAt).toLocaleDateString()}</p><button onClick={() => remove(template.id)} className="mt-4 rounded-lg bg-red-950 px-3 py-2 text-xs text-red-300">Delete</button></div>)}</div>
  </div>;
}
